#!/bin/bash

set -e

# cwd guaranteed to be repo by provisioner

# Make pnpm shut up about updates
export CI=true
# Environment variable makes pnpm put its store at __cache/.local/share/...
HOME=__cache pnpm --quiet install
pnpm -r build
./ts-to-js.sh